#strains and types of builds to run
strains: ['coronavirus_229E', 'coronavirus_HKU1', 'coronavirus_NL63', 'coronavirus_OC43']
builds_to_run: ["whole"]


exclude: "config/dropped_strains.txt"

files:
  color_schemes: "config/colors.tsv"
  latitude_longitude_schemes: "config/lat_longs.tsv"
  auspice_config: "config/auspice_config.json"
  reference_config:
    coronavirus_229E: "ingest/data/coronavirus_229E/reference.gbk" #to change
    coronavirus_HKU1: "ingest/data/coronavirus_HKU1/reference.gbk"
    coronavirus_NL63: "ingest/data/coronavirus_NL63/reference.gbk"
    coronavirus_OC43: "ingest/data/coronavirus_OC43/reference.gbk"
  clades_config:
    coronavirus_229E: "config/coronavirus_229E/clades_genome.tsv"
    coronavirus_HKU1: "config/coronavirus_HKU1/clades_genome.tsv"
    coronavirus_NL63: "config/coronavirus_NL63/clades_genome.tsv"
    coronavirus_OC43: "config/coronavirus_OC43/clades_genome.tsv"
  pathogen_config:
    coronavirus_229E: "ingest/data/coronavirus_229E/pathogen.json"
    coronavirus_HKU1: "ingest/data/coronavirus_HKU1/pathogen.json"
    coronavirus_NL63: "ingest/data/coronavirus_NL63/pathogen.json" 
    coronavirus_OC43: "ingest/data/coronavirus_OC43/pathogen.json" 
  sequence_annotation:
    coronavirus_229E: "ingest/data/coronavirus_229E/annotation.gff3"
    coronavirus_HKU1: "ingest/data/coronavirus_HKU1/annotation.gff3"
    coronavirus_NL63: "ingest/data/coronavirus_NL63/annotation.gff3"  
    coronavirus_OC43: "ingest/data/coronavirus_OC43/annotation.gff3" 

filter:
  group_by: "year country"
  min_coverage: 0.3
  subsample_max_sequences: 100 # set lower if you want to have a max sequences per group
  min_length: 
    coronavirus_229E: 16391 #length of 27317 60%
    coronavirus_HKU1: 17956 #length of 29926
    coronavirus_NL63: 16532 #length of  27553
    coronavirus_OC43: 18442 #length of 30738
  min_date: 100Y

align:
  allowed_mismatches: 10

refine:
  coalescent: "opt"
  date_inference: "marginal" 
  clock_filter_iqd: 10 
  clock_rate:
    coronavirus_229E: 0.000250
    coronavirus_HKU1: 0.000120
    coronavirus_NL63: 0.000120   
    coronavirus_OC43: 0.000250
  clock_std_dev: 
    coronavirus_229E: 0.00010
    coronavirus_HKU1: 0.00005
    coronavirus_NL63: 0.00005   
    coronavirus_OC43: 0.00010 

ancestral:
  inference: "joint"

traits:
  columns: "country"