#strains and types of builds to run
strains: ['adenovirus_b1', 'adenovirus_c2']
builds_to_run: ["whole"]


exclude: "config/dropped_strains.txt"

files:
  color_schemes: "config/colors.tsv"
  latitude_longitude_schemes: "config/lat_longs.tsv"
  auspice_config: "config/auspice_config.json"
  reference_config:
    adenovirus_b1: "ingest/data/adenovirus_b1/reference.gbk" #to change
    adenovirus_c2: "ingest/data/adenovirus_c2/reference.gbk" 
  clades_config:
    adenovirus_b1: "config/adenovirus_b1/clades_genome.tsv"
    adenovirus_c2: "config/adenovirus_c2/clades_genome.tsv"
  pathogen_config:
    adenovirus_b1: "ingest/data/adenovirus_b1/pathogen.json"
    adenovirus_c2: "ingest/data/adenovirus_c2/pathogen.json"
  sequence_annotation:
    adenovirus_b1: "ingest/data/adenovirus_b1/annotation.gff3"
    adenovirus_c2: "ingest/data/adenovirus_c2/annotation.gff3" 

filter:
  group_by: "year country"
  min_coverage: 0.3
  subsample_max_sequences: 100 # set lower if you want to have a max sequences per group
  min_length: 
    adenovirus_b1: 28270 #length of 35343
    adenovirus_c2: 28745 #length of 35937
  min_date: 100Y

align:
  allowed_mismatches: 10

refine:
  coalescent: "opt"
  date_inference: "marginal" 
  clock_filter_iqd: 10 

ancestral:
  inference: "joint"

traits:
  columns: "country"